### ISSUE TITLE
Lyre issue in connecting with native client

### ISSUE THREAD

**Issue by Su-s** [alexwiese/Lyre#13]
I had cloned lyre console test app and ran in in my system  installed lyre package from 

Get it on NuGet: PM> Install-Package Lyre

Build the c# app and add the reg keys in registry

When i ran upload the extension to chrome and try to execute it these two errors are blocking me 

![image](https://user-images.githubusercontent.com/37269911/74151593-7c8e5580-4c32-11ea-87db-a83f9a93586e.png)

![image](https://user-images.githubusercontent.com/37269911/74151609-8748ea80-4c32-11ea-86fe-389a26b536b2.png)

Please help.....

**Comment by alexwiese** [comment]
hey @Su-s 

First you need to make sure your registry key points to the right location for your `nativeMessagingManifest.json`. 

![image](https://user-images.githubusercontent.com/2103355/74205138-f91e4400-4cc5-11ea-86bf-3aee3a53890f.png)

Next you need to find the ID of your Chrome extension (go to Extensions in Chrome and find the ID: value).

![image](https://user-images.githubusercontent.com/2103355/74205042-7c8b6580-4cc5-11ea-9e04-ab2e75a8a109.png)

You need to modify your `nativeMessagingManifest.json` file to have the correct ID under the `allowed_origins`.

```
{
  "name": "com.my.cool.messaging.host",
  "description": "Lyre Console Test",
  "path": "C:\\git\\Lyre\\src\\Lyre.ConsoleTest\\bin\\Debug\\netcoreapp2.0\\win7-x64\\Lyre.ConsoleTest.exe",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://ghbmnnjooekpmoecnnnilnnbdlolhkhi/"
  ]
}
```

Make sure the path in your manifest file also corresponds with the path to your executable:
eg. something like `"path": "C:\\my-project\\bin\\debug\\my-project.exe"`

Please note that the name in the manifest must match the name in the registry entry, as well as the name used in your Chrome extension.
For example if you named your Native Messaging Host `com.my.cool.messaging.host` then you must:
 - use that name as the registry key 
 - use the name as the "name" field in the manifest file
 - use the name in the `background.js` file in your extension (the `hostName` that is passed to the `chrome.runtime.connectNative` method)

All the pieces have to come together.
Please note all of those requirements are specific to Chrome Native Messaging (not Lyre), so if you need help you can refer to the [documentation for Chrome Native Messaging](https://developer.chrome.com/extensions/nativeMessaging).

Let me know how you go!

**Comment by Su-s** [comment]
Hi 

**this is the registry value for json file, checked the location correct location is set.**

![image](https://user-images.githubusercontent.com/37269911/74212903-ad1ad180-4cbc-11ea-9284-511e9c4108dd.png)

**also had given the id for chrome extension, in the manifest file below**

![image](https://user-images.githubusercontent.com/37269911/74212926-c885dc80-4cbc-11ea-9fe7-e55471e1433c.png)

```
{
  "name": "native_messaging_app",
  "description": "Lyre Console Test",
  "path": "H:\\Sample Projects\\chromeextension\\lyreChrome\\native_messaging_app\\native_messaging_app\\obj\\Debug\\netcoreapp3.1\\native_messaging_app.exe",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://dllfmgicbkledhnakiobgbnfnockfkoc/"]
}
```

**verified the location of the exe file** 


**background.js file host name**
var hostName = "native_messaging_app";


**verified all these three names all the three are same.**
- use that name as the registry key
- use the name as the "name" field in the manifest file
- use the name in the background.js file in your extension (the hostName that is passed to the chrome.runtime.connectNative method)

**Comment by alexwiese** [comment]
When you update the registry you have to shut chrome down _completely_ and open it up again.
Sometimes closing all chrome windows and tabs isn't enough to shut Chrome down. It may be running in the background still.
So go into task manger and kill any running chrome.exe and then run chrome again so it picks up the registry change.

This path doesn't look right, I don't think you'd want to be running the exe from the obj folder, instead use the bin folder:

`H:\\Sample Projects\\chromeextension\\lyreChrome\\native_messaging_app\\native_messaging_app\\bin\\Debug\\netcoreapp3.1\\native_messaging_app.exe`

Also if Chrome is installed for all users the registry location is `HKEY_LOCAL_MACHINE\SOFTWARE\Google\Chrome\NativeMessagingHosts\` 
If it's not installed for all users the location is 
`HKEY_CURRENT_USER\SOFTWARE\Google\Chrome\NativeMessagingHosts\`

So make sure you're using the right registry location.

If that still doesn't work then try running `chrome.exe --enable-logging` so that it [enables logging](https://www.chromium.org/for-testers/enable-logging) and you can see any errors in the log file.

According to Google's documentation these are the potential reasons for getting that error:

> Specified native messaging host not found.
> Is the name spelled correctly in the extension and in the manifest file?
> Is the manifest put in the right directory and with the correct name? See native messaging host location for the expected formats.
> Is the manifest file in the correct format? In particular, is the JSON syntax correct and do the values match the definition of a native messaging host manifest?
> Does the file specified in path exist? On Windows, paths may be relative, but on OS X and Linux, the paths must be absolute.

**Comment by Su-s** [comment]
Thankyou @alexwiese 

it got worked

![image](https://user-images.githubusercontent.com/37269911/74234709-7b712d00-4cf3-11ea-9077-8e182b7a9c52.png)



is it possible to communicate between native app and chrome extension using lyre

**Comment by alexwiese** [comment]
What do you mean by native app? do you mean C or C++?

**Comment by Su-s** [comment]
> What do you mean by native app? do you mean C or C++?

meant native app is the host app for chrome extension is in c#

**Comment by alexwiese** [comment]
yeah that's what the example is doing. It's a C# program talking to a Chrome extension

**Comment by Su-s** [comment]
thankyou @alexwiese
